### ISSUE TITLE
NullPointerException at org.netbeans.modules.scala.core.ScalaParserResult

### ISSUE THREAD

**Issue by tzezula** [dcaoyuan/nbscala#100]
Stacktrace: 
java.lang.NullPointerException
   at org.netbeans.modules.scala.core.ScalaParserResult.<init>(ScalaParserResult.java:61)
   at org.netbeans.modules.scala.core.ScalaParserResult$.apply(ScalaParserResult.java:186)
   at org.netbeans.modules.scala.core.ScalaParser.parse(ScalaParser.java:109)

See https://netbeans.org/bugzilla/show_bug.cgi?id=240033 for details

**Comment by akochnev** [comment]
I looked into this and this issue should be closed - the bug was addressed with commit 295a1e88260d33a25436130604c3757e4076291e . I also tried to reproduce it using the note from @cminter (by using a scala class with a @native annotation) and the NPE isn't thrown. 

In addition, this is a pretty old issue, so if it was still active, we would be getting more reports in the first place.
