### ISSUE TITLE
SBT project does not import in Netbeans - NoSuchMethodError

### ISSUE THREAD

**Issue by rabejens** [dcaoyuan/nbscala#150]
I have an SBT 0.13.8 project with Scala 2.10.4. I added the plugin:

    addSbtPlugin("org.netbeans.nbsbt" % "nbsbt-plugin" % "1.1.4")

I then imported it, and I get:

    [info] About to create NetBeans project files for your project(s).
    java.lang.NoSuchMethodError: scalaz.Scalaz$.ToValidationV(Ljava/lang/Object;)Lscalaz/syntax/ValidationV;
    	at org.netbeans.nbsbt.core.package$.setting(package.scala:66)
    	at org.netbeans.nbsbt.core.NetBeans$.skipParents(NetBeans.scala:581)
    	at org.netbeans.nbsbt.core.NetBeans$$anonfun$action$1.apply$mcZ$sp(NetBeans.scala:108)
    	at org.netbeans.nbsbt.core.NetBeans$$anonfun$action$1.apply(NetBeans.scala:108)
    	at org.netbeans.nbsbt.core.NetBeans$$anonfun$action$1.apply(NetBeans.scala:108)
    	at scala.Option.getOrElse(Option.scala:120)
    	at org.netbeans.nbsbt.core.NetBeans$.action(NetBeans.scala:108)
    	at org.netbeans.nbsbt.core.NetBeans$$anonfun$netbeansCommand$2.apply(NetBeans.scala:87)
    	at org.netbeans.nbsbt.core.NetBeans$$anonfun$netbeansCommand$2.apply(NetBeans.scala:87)
    	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
    	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
    	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
    	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
    	at sbt.Command$.process(Command.scala:92)
    	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
    	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
    	at sbt.State$$anon$1.process(State.scala:184)
    	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
    	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
    	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    	at sbt.MainLoop$.next(MainLoop.scala:98)
    	at sbt.MainLoop$.run(MainLoop.scala:91)
    	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
    	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
    	at sbt.Using.apply(Using.scala:24)
    	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
    	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
    	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
    	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
    	at sbt.StandardMain$.runManaged(Main.scala:53)
    	at sbt.xMain.run(Main.scala:28)
    	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
    	at xsbt.boot.Launch$.withContextLoader(Launch.scala:129)
    	at xsbt.boot.Launch$.run(Launch.scala:109)
    	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:36)
    	at xsbt.boot.Launch$.launch(Launch.scala:117)
    	at xsbt.boot.Launch$.apply(Launch.scala:19)
    	at xsbt.boot.Boot$.runImpl(Boot.scala:44)
    	at xsbt.boot.Boot$.main(Boot.scala:20)
    	at xsbt.boot.Boot.main(Boot.scala)

What is going wrong here?

**Comment by rabejens** [comment]
I solved it. I still a reference to the sbteclipse plugin in my projects.sbt which caused the problems.
