### ISSUE TITLE
The SourcePathProviderImpl can not be created because of an IllegalArgumentException

### ISSUE THREAD

**Issue by entlicher** [dcaoyuan/nbscala#151]
See https://netbeans.org/bugzilla/show_bug.cgi?id=255499

The SourcePathProviderImpl can not be created because of:
Caused: java.lang.IllegalArgumentException: file:/....jar is not a valid classpath entry; use a jar-protocol URL.
	at org.netbeans.modules.java.classpath.SimplePathResourceImplementation.verify(SimplePathResourceImplementation.java:104)
	at org.netbeans.modules.java.classpath.SimplePathResourceImplementation.verify(SimplePathResourceImplementation.java:68)
	at org.netbeans.modules.java.classpath.SimplePathResourceImplementation.<init>(SimplePathResourceImplementation.java:131)
	at org.netbeans.spi.java.classpath.support.ClassPathSupport.createResource(ClassPathSupport.java:77)
	at org.netbeans.spi.java.classpath.support.ClassPathSupport.createClassPath(ClassPathSupport.java:126)
	at org.netbeans.modules.scala.debugger.projects.SourcePathProviderImpl.<init>(SourcePathProviderImpl.java:205)

The code need to catch IllegalArgumentException, like we do it in org.netbeans.modules.debugger.jpda.projects.SourcePathProviderImpl

**Comment by sworisbreathing** [comment]
The impact of this is pretty high. It causes the IDE to hang unrecoverably when it goes into debugger mode, even if I'm debugging a project that doesn't use scala. The only way to recover is to run `killall java` from the command line and relaunch the IDE.

In order for me to debug my project, I had to uninstall the plugin.
